// Fallback LinkedIn posts data (used when API is not configured or fails)
export const FALLBACK_LINKEDIN_POSTS = [
  {
    id: "fallback-1",
    title: "Beyond the Breakfast Bowl: Why Food Manufacturers Can't Afford to Ignore Asset Management",
    excerpt: "Discover how modern asset management is transforming the food manufacturing industry, from production efficiency to quality control.",
    date: "September 3, 2025",
    timestamp: 1725379200000,
    image: "/images/media/teamsolve-breakfast-blog-small.jpg.svg",
    linkedinUrl: "https://www.linkedin.com/company/teamsolvepteltd",
  },
  {
    id: "fallback-2",
    title: "AI-Driven Decentralized Water Solutions by HSL, TeamSolve, and Earthlab",
    excerpt: "Learn about our partnership bringing cutting-edge AI technology to decentralized water management systems.",
    date: "September 3, 2025",
    timestamp: 1725379200000,
    image: "/images/media/2.svg",
    linkedinUrl: "https://www.linkedin.com/company/teamsolvepteltd",
  },
  {
    id: "fallback-3",
    title: "TeamSolve secures Balibago Waterworks as first Philippines customer",
    excerpt: "Expanding our global reach, we're proud to bring Knowledge Twin technology to the Philippines water sector.",
    date: "September 3, 2025",
    timestamp: 1725379200000,
    image: "/images/media/3.svg",
    linkedinUrl: "https://www.linkedin.com/company/teamsolvepteltd",
  },
  {
    id: "fallback-4",
    title: "TeamSolve Featured in WWA: Knowledge Twin™ Implementation in Singapore",
    excerpt: "Our Knowledge Twin platform is recognized for its impact on water management in Singapore.",
    date: "September 3, 2025",
    timestamp: 1725379200000,
    image: "/images/media/4.svg",
    linkedinUrl: "https://www.linkedin.com/company/teamsolvepteltd",
  },
  {
    id: "fallback-5",
    title: "TeamSolve Announces Partnership with Mega Western Sales, Inc.",
    excerpt: "Strategic partnership to expand our reach in North American utility markets.",
    date: "August 15, 2025",
    timestamp: 1723680000000,
    image: "/images/media/5.svg",
    linkedinUrl: "https://www.linkedin.com/company/teamsolvepteltd",
  },
  {
    id: "fallback-6",
    title: "Generative AI Startup TeamSolve Raises Seed Round",
    excerpt: "TeamSolve secures funding backed by SGInnovate and Burnt Island Ventures to accelerate Knowledge Twin platform.",
    date: "July 28, 2025",
    timestamp: 1722124800000,
    image: "/images/media/6.svg",
    linkedinUrl: "https://www.linkedin.com/company/teamsolvepteltd",
  },
] as const;
