export const PARTNERS_SECTION = {
  title: "Partnering with Utility Teams Globally",
  partners: [
    {
      id: "hrsd",
      logo: "/images/partners/hrsd.svg",
      logoAlt: "HRSD",
      location: "USA",
      name: "Hampton Roads Sanitation District (HRSD)",
      useCase: "Operational Insights",
    },
    {
      id: "southington",
      logo: "/images/partners/southingtonWaterDepartment.svg",
      logoAlt: "Southington Water Department",
      location: "USA",
      name: "Southington Water Department (SWD)",
      useCase: "Operational Insights; Workflow Automation",
    },
    {
      id: "howard-county",
      logo: "/images/partners/howardCounty.svg",
      logoAlt: "Howard County",
      location: "USA",
      name: "Howard County, Maryland",
      useCase: "Operational Insights; Workflow Automation",
    },
    {
      id: "south-fort-collins",
      logo: "/images/partners/southFortCollins.svg",
      logoAlt: "South Fort Collins Sanitation District",
      location: "USA",
      name: "South Fort Collins Sanitation Dist (SFCSD)",
      useCase: "Operational Insights",
    },
    {
      id: "midland",
      logo: "/images/partners/midland.svg",
      logoAlt: "Midland Ontario",
      location: "CANADA",
      name: "Midland (Ontario)",
      useCase: "Operational Insights",
    },
    {
      id: "balibago",
      logo: "/images/partners/baliBago.svg",
      logoAlt: "Balibago Waterworks",
      location: "PHILIPPINES",
      name: "Balibago Waterworks",
      useCase: "Operational Insights; Workflow Automation",
    },
    {
      id: "fiji",
      logo: "/images/partners/fiji.svg",
      logoAlt: "Water Authority of Fiji",
      location: "FIJI",
      name: "Water Authority of Fiji",
      useCase: "Operational Insights; Workflow Automation",
    },
    {
      id: "rand-water",
      logo: "/images/partners/randWater.svg",
      logoAlt: "Rand Water",
      location: "S. AFRICA",
      name: "Rand Water",
      useCase: "Operational Insights",
    },
    {
      id: "pia",
      logo: "/images/partners/pia.svg",
      logoAlt: "Pipeline Inspection",
      location: "GLOBAL",
      name: "Pipeline Inspection",
      useCase: "Operational Insights; Workflow Automation",
    },
    {
      id: "wannon-water",
      logo: "/images/partners/wannonWater.svg",
      logoAlt: "Wannon Water",
      location: "AUSTRALIA",
      name: "Wannon Water",
      useCase: "Operational Insights; Workflow Automation",
    },
    {
      id: "urban-utilities",
      logo: "/images/partners/urbanUtilities.svg",
      logoAlt: "Urban Utilities",
      location: "AUSTRALIA",
      name: "Urban Utilities",
      useCase: "Operational Insights; Workflow Automation",
    },
    {
      id: "earth-lab",
      logo: "/images/partners/earthLab.svg",
      logoAlt: "Earth Lab",
      location: "SE ASIA",
      name: "Earth Lab",
      useCase: "Operational Insights; Workflow Automation",
    },
  ],
} as const;
