export const PRICING_PLANS = {
  trial: {
    id: "trial",
    name: "Trial Environment",
    price: "Free",
    period: "for 30 days",
    description: "Ideal for teams who want hands-on experience before scaling.",
    subtitle: undefined,
    bestFor: "Testing workflows, data ingestion, & AI insights with real operational data.",
    features: [
      "Upload CMMS exports, time-series data, documents, SOPs",
      "Guided mobile forms for field capture",
      "AI-powered search & Q&A across uploaded data",
      "Up to 10 users",
      "Secure, isolated trial environment",
    ],
    buttonText: "Book a Demo",
    buttonHref: "/contact",
    buttonVariant: "outline" as const,
    highlighted: false,
  },
  team: {
    id: "team",
    name: "Team",
    price: "Custom Pricing",
    period: "",
    description: "One-time Implementation Fee + Annual Subscription",
    subtitle: "A ready-to-deploy system-in-a-box, tailored to how your teams actually work.",
    bestFor: "Multiple use cases within a single department",
    features: [
      "Full CMMS integration",
      "Time-series data integration based on use case",
      "Automated workflows, approvals, and reporting",
      "AI Knowledge Assistant trained on your data",
      "Mobile-first field capture (online & offline)",
    ],
    buttonText: "Book a Demo",
    buttonHref: "/contact",
    buttonVariant: "default" as const,
    highlighted: true,
    badge: "Popular",
  },
  enterprise: {
    id: "enterprise",
    name: "Enterprise",
    price: "Contact Us",
    period: "",
    description: "One-time Implementation Fee + Annual Subscription",
    subtitle: "Designed for multi-department or multi-site organizations with advanced requirements.",
    bestFor: "Utilities & facility operators operating at scale.",
    features: [
      "Everything in Team, plus:",
      "Multi-site and multi-department deployment",
      "Custom integrations & APIs",
      "Advanced security & deployment options (cloud / hybrid / on-prem)",
      "Dedicated onboarding & support",
    ],
    buttonText: "Get started",
    buttonHref: "/contact",
    buttonVariant: "outline" as const,
    highlighted: false,
  },
} as const;

export const PRICING_CTA = {
  title: "Try Knowledge Twin Free for 30 Days",
} as const;
